/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/14fc7950-5058-4d6b-aa50-6f23e53ccec0 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float humidity;
  float illuminance;
  float pressure;
  float temperature;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <WiFiNINA.h>
#include "EnvShieldSensors.h"
#include "ShellyPlug.h"

const float LOW_HUMIDIFIER = 32.0;
const float HIGH_HUMIDIFIER = 35.0;
char ssid[] = SECRET_SSID;        // your network SSID (name)
char pass[] = SECRET_PASS;    // your network password (use for WPA, or use as key for WEP)
int status = WL_IDLE_STATUS;     // the Wifi radio's status
EnvShieldSensors env;
ShellyPlug plug(SECRET_SHELLY_PLUG_HUMIDIFIER_IP);

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  while (status != WL_CONNECTED) {
    Serial.print("Attempting to connect to network: ");
    Serial.println(ssid);
    // Connect to WPA/WPA2 network:
    status = WiFi.begin(ssid, pass);

    // wait 10 seconds for connection:
    delay(10000);
  }

  // you're connected now, so print out the data:
  printWifiData();

  if (!env.begin()) 
  {
    Serial.println("Failed to initialize MKR ENV shield!");
    while (1);
  }

  plug.off();
  plug.on();
  bool state;
  if (plug.getState(state)) {
      Serial.print("Shelly state: ");
      Serial.println(state ? "ON" : "OFF");
  }
}

void loop() {
  ArduinoCloud.update();
  env.readEnvData();
  env.printEnvData();
  humidity = env.humidity;
  temperature = env.temperature;
  pressure = env.pressure;
  illuminance = env.illuminance;
  controlHumidity();
  delay(10000);
}

//In future it will make sense to have a controller class
void controlHumidity(){
  Serial.println("Humidity is:");
  Serial.print(humidity);
  if (humidity < LOW_HUMIDIFIER){
    plug.on();
  } else if (humidity > HIGH_HUMIDIFIER)
  {
    plug.off();
  }
}

void printWifiData() {
  Serial.println("You're connected to the network");
  Serial.println("----------------------------------------");
  Serial.println("Board Information:");
  // print your board's IP address:
  IPAddress ip = WiFi.localIP();
  Serial.print("IP Address: ");
  Serial.println(ip);

  Serial.println();
  Serial.println("Network Information:");
  Serial.print("SSID: ");
  Serial.println(WiFi.SSID());

  // print the received signal strength:
  long rssi = WiFi.RSSI();
  Serial.print("signal strength (RSSI):");
  Serial.println(rssi);

  byte encryption = WiFi.encryptionType();
  Serial.print("Encryption Type:");
  Serial.println(encryption, HEX);
  Serial.println();
  Serial.println("----------------------------------------");
}

/*
  Since Humidity is READ_WRITE variable, onHumidityChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onHumidityChange()  {
  // Add your code here to act upon Humidity change
  Serial.println("Humidity Changed");
}

/*
  Since Temperature is READ_WRITE variable, onTemperatureChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTemperatureChange()  {
  // Add your code here to act upon Temperature change
}

/*
  Since Pressure is READ_WRITE variable, onPressureChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onPressureChange()  {
  // Add your code here to act upon Pressure change
}

/*
  Since Illuminance is READ_WRITE variable, onIlluminanceChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onIlluminanceChange()  {
  // Add your code here to act upon Illuminance change
}


